version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - JWT_SECRET
      - CHURRASCO_SMS
      - CHURRASCO_SMS_MASTER
      - DATABASE_URL
      - DATABASE_HOST
      - DATABASE_PORT
      - DATABASE_NAME
      - DATABASE_USERNAME
      - DATABASE_PASSWORD

    volumes:
      - .:/app
    restart: always