version: '3.8'

services:
  app:
    image: guialexandre/meu-barbeiro-api:latest
    container_name: meu-barbeiro-api
    ports:
      - "3000:3000"
    env_file:
      - /home/meu-barbeiro-api/.env
    restart: always

  susuzeira-api:
    image: guialexandre/meu-barbeiro-api:latest
    container_name: susuzeira-api
    ports:
      - "4000:3000"
    env_file:
      - /home/meu-barbeiro-api/susuzeira-api.env
    restart: always
