version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - /home/meu-barbeiro-api/.env
    volumes:
      - .:/app
    restart: always