### Criar usuário
POST http://localhost:3000/api/users
Content-Type: application/json

{
    "name": "Caio",
    "password": "123",
    "contactNumber": "19999999999",
    "password": "101215",
    "role": "client"
}

### Buscar usuário
GET http://localhost:3000/api/users?page=1&total=2
