### Login
POST http://localhost:3000/api/services
Content-Type: application/json

{
    "name": "Corte",
    "description": "",
    "price": 30.0,
    "timeExecution": 30
}

### Remover serviço
DELETE http://localhost:3000/api/services/d9755e37-4470-416a-b5bd-b02fa73e1748
Content-Type: application/json


### Buscar serviços
GET http://localhost:3000/api/services?search=&status=ativo
Content-Type: application/json

### Buscar atualiza descrição
PATCH  http://localhost:3000/api/services/19b35e29-c060-4798-bf14-c3d110770287
Content-Type: application/json

{
    "name": "Hidratação",
    "description": "Hidratação"
}

### Buscar serviços client
GET http://localhost:3000/services/prices
Content-Type: application/json

### Buscar serviços por id
GET http://localhost:3000/services/dab1ab0a-edd7-49b7-be52-af4df7eed58f
Content-Type: application/json