### Login
POST http://localhost:3000/services
Content-Type: application/json

{
    "name": "Alisamento",
    "description": "Alisamento + Hidratação",
    "amount": 35.0,
    "time_execution": 40
}
# {
#     "name": "Hidratação",
#     "description": "",
#     "amount": 20.0,
#     "time_execution": 15
# }
# {
#     "name": "Barba",
#     "description": "",
#     "amount": 20.0,
#     "time_execution": 15
# }
# {
#     "name": "Progressiva",
#     "description": "Progessiva + Hidratação",
#     "amount": 80.0,
#     "time_execution": 70
# }
# {
#     "name": "Corte",
#     "description": "",
#     "amount": 30.0,
#     "time_execution": 30
# }

### Buscar serviços
GET http://localhost:3000/services
Content-Type: application/json

### Buscar serviços por id
GET http://localhost:3000/services/dab1ab0a-edd7-49b7-be52-af4df7eed58f
Content-Type: application/json