name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Execute remote SSH commands using SSH key
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.VPS_IP }}
          username: "root"
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "."
          target: "/home/meu-barbeiro-api"

      # Conectar à VPS e executar o deploy
      - name: Execute remote SSH commands using SSH key
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/meu-barbeiro-api
            docker-compose down
            docker-compose up --build -d