name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Execute remote SSH commands using SSH key
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_IP }}
          username: "root"
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "."
          target: "deploy/meu-barbeiro-api"

      # Conectar à VPS e executar o deploy
      - name: Deploy on VPS
        run: |
          ssh root@${{ secrets.VPS_IP }} << 'EOF'
          cd /home/deploy/meu-barbeiro-api
          docker-compose down
          docker-compose up --build -d
          EOF