name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout do código
      - name: Checkout code
        uses: actions/checkout@v3

      # Login no Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Construir a imagem Docker
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/meu-barbeiro-api:latest -f .docker/Dockerfile .

      # Enviar a imagem para o Docker Hub
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/meu-barbeiro-api:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Conectar à VPS e atualizar o serviço
      - name: Deploy on VPS
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_IP }}
          username: 'root'
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/meu-barbeiro-api
            docker-compose pull
            docker-compose down
            docker-compose up -d --force-recreate
